export const ROLES = {
  ADMIN: "ADMIN",
  RECEPTIONIST: "RECEPTIONIST",
  STUDENT: "STUDENT",
  DIRECTOR: "DIRECTOR",
};

export const CREATABLE_BY_ADMIN = [
  ROLES.RECEPTIONIST,
  ROLES.DIRECTOR,
  ROLES.STUDENT,
];
